### ISSUE TITLE
[Bug] UI Fehler bei Löschen eines Lernelements in der Lernwelt im mittleren Fenster via Kontextmenü nach zwei oder mehrmaligem Rechtsklick

### ISSUE THREAD

**Issue by BujusKrachus** [ProjektAdLer/Autorentool#595]
## Beschreibung des Problems:
UI Fehler bei löschen eines Lernelements in der Lernwelt im mittleren Fenster via Kontextmenü nach zwei oder mehrmaligem Rechtsklick
## Schritte zum Reproduzieren:
- Lernwelt öffnen
- Lernraum im mittleren Fenster öffnen
- Rechtsklick auf ein Lernelement, sodass sich das Kontextmenü öffnet
- erneuter Rechtsklick auf das selbe Lernelement (kein Doppelklick)
- Klick im Kontextmenü auf Delete
- Rotes Feld Neu Laden erscheint
## Erwartetes Verhalten:
Kein Fehler
## Tatsächliches Verhalten:
Fehler, siehe Log:
<details>
  <summary>Crash log</summary>

```
2024-09-01 17:34:08.886 +02:00 [VRB] Deleted LearningElement Adaptivitätselement ("28fae8c0-41e2-432f-801b-4e36f69babe2") in LearningSpace Autorentool ("dc26e59b-e50c-4487-b4b9-f3e77b2a54da")
2024-09-01 17:34:08.886 +02:00 [VRB] Logging LearningSpace to ILearningSpaceViewModel
2024-09-01 17:34:08.886 +02:00 [VRB] LearningElement set to null with id null
2024-09-01 17:34:08.886 +02:00 [VRB] ActiveSlotInSpace set to -1
2024-09-01 17:34:08.886 +02:00 [WRN] Unhandled exception rendering component: Sequence contains no matching element
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Presentation.PresentationLogic.DropZone.LearningElementDropZoneHelper.<>c__DisplayClass15_0.<IsItemInDropZone>g__CheckInDropZone|2(String dropzoneType, IDictionary`2 dict) in D:\a\Autorentool\Autorentool\Presentation\PresentationLogic\DropZone\LearningElementDropZoneHelper.cs:line 73
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at MudBlazor.MudDropZone`1.GetItems()
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.887 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Presentation.PresentationLogic.DropZone.LearningElementDropZoneHelper.<>c__DisplayClass15_0.<IsItemInDropZone>g__CheckInDropZone|2(String dropzoneType, IDictionary`2 dict) in D:\a\Autorentool\Autorentool\Presentation\PresentationLogic\DropZone\LearningElementDropZoneHelper.cs:line 73
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at MudBlazor.MudDropZone`1.GetItems()
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.887 +02:00 [DBG] Removed entry for "4202bf49-6760-47ff-8fa6-ae48eeff8d4e". 0 total observers after remove.
2024-09-01 17:34:08.888 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.888 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
   at MudBlazor.MudDropZone`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-09-01 17:34:08.889 +02:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
2024-09-01 17:34:08.889 +02:00 [ERR] Unhandled exception in circuit 'e8RhGKicEPNBFVP9tPZ8rWra877VF2Rxu_r0TnemdQA'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

</details>

## Ansprechpartner:
(für weitere Fragen)
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by BujusKrachus** [comment]
![grafik](https://github.com/user-attachments/assets/ba4c462b-42b3-4a6e-b3e2-d7f302032b23)
